# Site setings
name: "Jun Hou"
description: "Personal website of Jun Hou, a PhD student and researcher focusing on trustworthy AI, multimodal learning, and causality."
meta_description: "Jun Hou, PhD student and researcher in trustworthy and explainable AI, causal inference, and multimodal learning."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://JuneHou.github.io
disqus: ""
mailchimp_url: ""
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics:

# Author
author:
  name: "Jun Hou"
  image: "authorimage.jpg"
  greetings: "Hi there!"
  description: "I am Jun Hou, a researcher specializing in multimodal learning, trustworthy AI, and explainable AI, currently focusing on debiasing with causal inference. 
  My research aims to enhance AI generalizability and interpretability, particularly in healthcare applications."

# Contact form setings
email: junh@vt.edu
contact_page_description: "Please feel free to contact me if we share the same research interests or personal interests. I will get back to you as soon as possible."
thankyou_page_description: "Your message has been successfully sent. Jun will contact you very soon!"

# Social links
#twitter: "username"
#facebook: "username"
github: "https://github.com/JuneHou"
#codepen: "username"
#dribbble: "username"
#medium: "@username"
#instagram: "username"
#pinterest: "username"
linkedin: "https://www.linkedin.com/in/jun-hou-1392b8149/"
producthunt: "https://scholar.google.com/citations?user=4XvcYKEAAAAJ&hl=en"

# Navigation
navigation:
  - text: About
    url: /about
  - text: Archive
    url: /tags
  - text: Style Guide
    url: /style-guide

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
